### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Lukas-Batema**
This very basic structure of security vulnerability reporting, shows the base on what a file of such should look like. This may be changed at any time, if so desired by the owner!

### CODE REVIEW

**Comment by pd4d10** [comment]
Thanks for your contribution!

I'm not quite sure what this guide is used for. Could you explain a bit more?

**Comment by Lukas-Batema** [comment]
Dear @pd4d10,
This is used for a basic structure of a security vulnerability reporting file. This will be what pops up when users select the report a vulnerability in the issues creation section.

Best Wishes,
Lukas Batema

**Comment by Lukas-Batema** [comment]
> Thanks for your contribution!
> 
> I'm not quite sure what this guide is used for. Could you explain a bit more?

Dear @pd4d10,
Do you need me to change anything, or is this gonna be closed without merge? Thank you!

Best Wishes,
Lukas Batema

**Comment by pd4d10** [comment]
Oh, I didn't use this before. Is there any documentation of how it works?

**Comment by Lukas-Batema** [comment]
> Oh, I didn't use this before. Is there any documentation of how it works?

Dear @pd4d10,
[Here](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) is the documentation.

> _Best Wishes,
>Lukas Batema_
>
>-------
>
>@Lukas-Batema, @PedestriaMC-Network
>
>-------
>
>_(Grade 10, JavaScript and Java Programmer, and Front End Web Designer)_
>
>-------
>
>_**[Pedestriapedia Official](https://wiki.pedestriamc.com/)**_
>_**[BatemaDevelopment](https://lukas-batema.github.io/BatemaDevelopment/)**_
>_**[My Portfolio](https://github.com/Lukas-Batema/README.md/)**_

**Pull request merged**
