### PR TITLE
feat: add button to quickly switch accounts

### LINKED ISSUE #35: Quickly switch between accounts
Currently it is unfortunately not possible to quickly switch between accounts. Maybe something like long-pressing the "Me" tabbar item could bring up an account switcher?

If this idea is liked, I could also work on this myself!

### PR DESCRIPTION
**Pull request by phillipthelen**
Fixes #35 

I had to do this slightly hacky, since the way BottomMenuItem works, does not allow it to be wrapped in a gesturerecognizer. So I wrapped the icon and text widgets individually. This does seem to work pretty well though.

As described in the issue, this PR adds a long-press gesture to the "Me" tabbar item. It brings up a bottom modal where you can quickly choose a different account. Choosing the currently active one doesn't reload the app but instead just closes the modal. I also added a "Manage" link, that opens the regular login view where the user can also add new accounts or delete existing ones.

Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-12 at 10 19 41 Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-12 at 10 19 56

### CODE REVIEW

**Comment by pd4d10** [comment]
Thanks for your contribution! I'll review it ASAP

**Comment by pd4d10** [comment]
Hi, @phillipthelen , sorry for the late review. This feature is really helpful!

Perhaps there is a point that can be improved that the entry is a bit hidden(long press Me tab item). Most users may not notice this behavior.

If you don't mind I'd like to add some commits to this PR to give users some tips for this feature.

**Comment by phillipthelen** [comment]
I 100% agree with you! Do you have an idea for how to better surface this feature? Are there other places in the app where tutorials/hints are shown?

**Comment by pd4d10** [comment]
Hi, @phillipthelen , sorry for the long wait.

I still don't figure out how to add the hints. Instead of that, my new proposal is to add a 'switch accounts' button to the `Me` screen's header. It also works for quick account switch. The only drawback is that it would appear a bit slowly (waiting for user data fetching), and not work offline.

The code base has changed significantly after 8 months, which would cause lots of conflicts on merge/rebase, so I'm going to rewrite these code and force push to this PR's branch.

**Comment by pd4d10** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-08 at 17 06 28

**Comment by pd4d10** [comment]
Thank you for all your efforts!

Feel free to ping me if there are other ideas

**Pull request merged**
