### PR TITLE
feat: files screen

### LINKED ISSUE #74: Files changed screen in a PR
Hi @pd4d10,
So I'm trying to add a `Files Changed Screen` instead of redirecting to the web. This is an example [response](https://api.github.com/repos/git-touch/git-touch/pulls/72/files).

The modified text is in `patch`.

`\n` followed by + indicates an addition and similarly `\n` followed by - indicates deletion.

My idea is to split it on `\n` and every list item that starts with a `+` I'm thinking of wrapping with Text with green color and similarly red color for `-`.  Is this a right approach or would you suggest an alternative way? 

Also I'm unable to understand the starting portion of the patch. I know it has something to do with the line number. Take the first item of the example [response](https://api.github.com/repos/git-touch/git-touch/pulls/72/files)
`@@ -313,3 +313,15`. 

Do you have an idea? 

I'll put a list of files with a drop-down for every file which will expand to display the changes.

### PR DESCRIPTION
**Pull request by shreyas1599**
Fixes #74 

- I'm currently working on `GistsScreen` as well, so `router.dart` and `github.dart` includes portions for that(not completed yet). I should've done that on a separate branch :/. Should I add a commit to comment the `gists` portion out?
- I'll open a pr asap for `GistsScreen`
- I had to use the `Card` widget in `files_item.dart` as `ExpansionTile` required a parent that is a material widget. `Container` didn't work.

This is how it looks: 

image
image

### CODE REVIEW

**Comment by pd4d10** [comment]
Since this screen is only for viewing file changes, perhaps we could add a button to *view in the browser*? For someone who wants to get the full features of the GitHub web version, e.g. submit a review.

**Comment by pd4d10** [comment]
Or use the `share` module to open the system share panel, which has *open in the browser* included.

**Comment by shreyas1599** [comment]
`Open in browser` does not seem to appear in the share sheet. Should I use `url_launcher` instead?

**Comment by pd4d10** [comment]
https://github.com/git-touch/git-touch/blob/0063e99bbcfef81fbe0e0388289ceb40afeab40d/lib/screens/gh_repo.dart#L89-L105

**Comment by shreyas1599** [comment]
Sorry the first commit, action url was incomplete

**Pull request merged**
