### PR TITLE
feat: localization

### PR DESCRIPTION
**Pull request by shreyas1599**
#119 

- I did not add a few messages to the .arb files as the general syntax is to use `S.of(context).getter` while a few messages that required translations were present outside a widget and hence I could not use `.of(context)` for such messages. (Still figuring this out) _(in a nutshell: cannot translate text present outside a widget)_
- Added support for hindi(hi) - the only other language I can read
- Used the VS Code `Flutter Intl` extension. Easier to write translations.  [Demo](https://twitter.com/localizely/status/1255175275454881793) 
- The output localization file is called `S.dart` as the extension as seen in the demo replaces the highlighted text with `S.context(of)...`
- Now will be easy to add translations for other languages. (Copy the template from one of the .arb files and change the value of the key-value pair)
- Better to use the extension to create/delete arb files. Easier as it updates all the files whenever you replace text with `S.context(of)...` as seen in the demo.
- _Possible improvement_: Reduce mappings in the arb files by identifying the plural of a word. For example, now I have separate mappings for repository and repositories
- Can I update `contributing.md` with steps to follow in case anyone wants to add translation for a language? (They only have to use the extension and translate the messages in the arb file)

### CODE REVIEW

**Comment by pd4d10** [comment]
Thanks! I'll take a look ASAP

> Can I update contributing.md

Of course

**Comment by pd4d10** [comment]
Hi, @shreyas1599 , which Flutter version are you using?

I checked out the branch and there seem to be some build errors

image

**Comment by shreyas1599** [comment]
> which Flutter channel/version are you using?

1.22.1 on the stable channel and Dart SDK version: 2.10.3 (stable)

**Comment by pd4d10** [comment]
OK. I'll check it later

**Comment by pd4d10** [comment]
Great work!

Let's track the potential improvements with a new issue: https://github.com/git-touch/git-touch/issues/139

**Pull request merged**
