### PR TITLE
chore: synthetic packages for i18n

### LINKED ISSUE #185: Use Synthetic Packages for localizations
https://github.com/flutter/gallery/pull/282

> With synthetic package support in the gen_l10n tool (flutter/flutter#62395), we no longer need to check in generated localizations .dart files into any Flutter project

### PR DESCRIPTION
**Pull request by shreyas1599**
Closes #185

Apart from this,

- added `es` `pt` `nb` to `supportedLocales` list
- 3 new files `intl_nb`, `intl_zh`, `intl_pt` - required as fallback languages (without the country code).

### CODE REVIEW

**Comment by pd4d10** [comment]
So efficient!

**Comment by pd4d10** [comment]
image

`flutter run` still generates these files. Just wondering if this is as expected

**Comment by shreyas1599** [comment]
> `flutter run` still generates these files. Just wondering if this is as expected

It does not generate the files for me. Maybe it's a one time thing? Did you try deleting the files and running it again?

**Comment by pd4d10** [comment]
OK, I'll try it later

**Pull request merged**
